# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-29 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='open_for_enrollment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='semester',
            field=models.IntegerField(choices=[(1, b'First Semester'), (2, b'Second Semester'), (3, b'Summer')]),
        ),
    ]
