# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-29 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sais', '0002_auto_20160529_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stsbracket',
            name='bracket',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
