# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-24 07:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('acronym', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code_name', models.CharField(max_length=30)),
                ('course_no', models.IntegerField()),
                ('block', models.CharField(max_length=10)),
                ('start_hour_time', models.IntegerField()),
                ('start_min_time', models.IntegerField()),
                ('end_hour_time', models.IntegerField()),
                ('end_min_time', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('prerequisite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_instituted', models.DateTimeField()),
                ('courses', models.ManyToManyField(to='student.Course')),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.FloatField()),
                ('paid', models.BooleanField(default=False)),
                ('academic_calendar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.AcademicYear')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Campus')),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tuition_subsidy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='STSBracket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('bracket', models.CharField(max_length=3, unique=True)),
                ('tuition_subsidy', models.FloatField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(unique=True)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('up_mail', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(max_length=7)),
                ('admitted_campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Campus')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='stsbracket',
            name='beneficiary',
            field=models.ManyToManyField(to='student.Student'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='beneficiary',
            field=models.ManyToManyField(to='student.Student'),
        ),
        migrations.AddField(
            model_name='enrollmenttransaction',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='program',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.Program'),
        ),
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Professor'),
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Program'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, to='student.Student'),
        ),
    ]
