# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-29 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sais', '0003_auto_20160529_1752'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolledCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(choices=[(1.0, b'1.00'), (1.25, b'1.25'), (1.5, b'1.50'), (1.75, b'1.75'), (2.0, b'2.00'), (2.25, b'2.25'), (2.5, b'2.50'), (2.75, b'2.75'), (3.0, b'3.00'), (4.0, b'4.00'), (5.0, b'5.00'), (6.0, b'INC'), (7.0, b'NO GRADE'), (8.0, b'DROPPED')], default=7.0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sais.CourseOffered')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
        migrations.RemoveField(
            model_name='enlistedcourse',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='enlistedcourse',
            name='is_enrolled',
        ),
    ]
