# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-29 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sais', '0004_auto_20160529_2106'),
        ('student', '0002_auto_20160529_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sais.AcademicYear')),
            ],
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='academic_calendar',
            new_name='term',
        ),
        migrations.AlterField(
            model_name='enlistedcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlisted', to='sais.CourseOffered'),
        ),
        migrations.AlterField(
            model_name='enlistedcourse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlisted_courses', to='student.Student'),
        ),
        migrations.AlterField(
            model_name='enrolledcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled', to='sais.CourseOffered'),
        ),
        migrations.AlterField(
            model_name='enrolledcourse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_courses', to='student.Student'),
        ),
    ]
